// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isndnugianoasldjvihf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzbmRudWdpYW5vYXNsZGp2aWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTE3ODQsImV4cCI6MjA2NDg4Nzc4NH0.Go62XoDw5_0Dg5ypZd4BnH0NtKvljzs2Zs2oUZJOJ-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);